// All UI strings in Bahasa Indonesia as per SPEC
const id = {
  appName: 'FlashMind',
  tagline: 'Alat bantu pembelajaran Anda',
  'hero.ctaLogin': 'Masuk untuk uji coba!',
  'hero.ctaRegister': 'Daftar untuk membuat akun baru',
  'hero.noteDifferent': 'masuk uji coba berbeda dengan memakai akun',
  'hero.scrollHint': 'scroll/swipe ke bawah untuk informasi lebih lanjut',
  'hero.howItHelps': 'Bagaimana FlashMind membantu?',
  'hero.howItHelpsBody': 'FlashMind mengubah catatan Anda dibentuk seperti kartu belajar.',
  'hero.research': 'Penelitian menunjukkan metode belajar ini sangat efektif.',
  'hero.ctaDontWait': 'Jangan tunggu lagi, segera',
  'auth.toggleLogin': 'Masuk',
  'auth.toggleRegister': 'Daftar',
  'auth.email': 'Surel',
  'auth.password': 'Kata sandi',
  'auth.passwordConfirm': 'Konfirmasi kata sandi',
  'auth.firstName': 'Nama Depan',
  'auth.lastName': 'Nama Belakang',
  'auth.gender': 'Jenis Kelamin',
  'auth.genderMale': 'Laki-laki',
  'auth.genderFemale': 'Perempuan',
  'auth.genderOther': 'Lainnya',
  'auth.submitLogin': 'Masuk',
  'auth.submitRegister': 'Daftar',
  'auth.google': 'Masuk dengan Google',
  'dashboard.title': 'Kartu Belajar Saya',
  'dashboard.empty': 'Belum ada kartu belajar',
  'dashboard.newManual': '+ Kartu Baru',
  'dashboard.aiGen': '✨ Buat dengan AI',
  'flashcard.front': 'Judul',
  'flashcard.back': 'Catatan',
  'flashcard.delete': 'Hapus',
  'flashcard.save': 'Simpan',
  'flashcard.close': 'Tutup',
  'ai.promptLabel': 'Catatan Anda',
  'ai.generate': 'Hasilkan',
  'ai.loading': 'Memuat…',
  'ai.noKey': 'Fitur AI belum dikonfigurasi',
  'ai.failed': 'AI gagal membuat kartu',
  'admin.title': 'Admin',
  'admin.keyPlaceholder': 'Kunci API admin',
  'admin.saveKey': 'Simpan kunci',
  'admin.clearKey': 'Hapus kunci',
  'admin.stats': 'Statistik',
  'admin.totalUsers': 'Total pengguna',
  'admin.totalGuests': 'Total tamu',
  'admin.totalCards': 'Total kartu',
  'admin.latestTraces': 'Jejak terbaru',
  'error.required': 'Wajib diisi',
  'error.emailInvalid': 'Format surel tidak valid',
  'error.passwordShort': 'Kata sandi minimal 8 karakter',
  'error.passwordMismatch': 'Kata sandi tidak cocok',
  'error.unauthorized': 'Tidak diizinkan',
  'error.network': 'Koneksi bermasalah',
  'error.serverError': 'Terjadi kesalahan server',
  'error.tooManyRequests': 'Terlalu banyak permintaan',
  'footer.credit': '© FlashMind',
} as const;

export default id;

export function t(key: keyof typeof id): string {
  return id[key];
}