// All UI strings in Bahasa Indonesia as per SPEC
const id = {
  appName: 'FlashMind',
  tagline: 'Alat bantu pembelajaran Anda',
  'hero.ctaLogin': 'Masuk untuk uji coba!',
  'hero.ctaRegister': 'Daftar untuk membuat akun baru',
  'hero.ctaGuest': 'Masuk uji coba (tamu)',
  'hero.ctaOpenDashboard': 'Buka Dasbor',
  'hero.noteDifferent': 'masuk uji coba berbeda dengan memakai akun',
  'hero.scrollHint': 'scroll/swipe ke bawah untuk informasi lebih lanjut',
  'hero.howItHelps': 'Bagaimana FlashMind membantu?',
  'hero.howItHelpsBody': 'FlashMind mengubah catatan Anda dibentuk seperti kartu belajar.',
  'hero.research': 'Penelitian menunjukkan metode belajar ini sangat efektif.',
  'hero.ctaDontWait': 'Jangan tunggu lagi, segera',
  'hero.problemTitle': 'Catatan menumpuk. Ingatan cepat hilang.',
  'hero.problemBody': 'Anda membaca ulang, meng-highlight, menyalin — lalu lupa seminggu kemudian. Bukan salah Anda. Metode pasif tidak melatih otak untuk mengingat.',
  'hero.solutionTitle': 'Belajar aktif, bukan membaca ulang.',
  'hero.solutionBody': 'FlashMind mengubah catatan Anda menjadi kartu belajar. Anda menjawab, bukan sekadar membaca. Setiap kartu memperkuat ingatan lewat Active Recall.',
  'hero.demoTitle': 'Coba sekarang. Tanpa daftar.',
  'hero.demoBody': 'Klik kartu di samping. Rasakan sendiri bagaimana satu kartu bisa menempel di kepala dalam hitungan detik.',
  'hero.proofTitle': 'Bukti, bukan janji.',
  'hero.proofBody': 'Riset dari Karpicke & Roediger (2008) menunjukkan Active Recall meningkatkan retensi hingga 50% dibanding membaca ulang. Metode kartu belajar adalah standar di dunia medis, hukum, dan bahasa.',
  'hero.benefitFast': 'Cepat',
  'hero.benefitFastBody': 'Buat kartu dari catatan apa pun dalam satu klik.',
  'hero.benefitSmart': 'Pintar',
  'hero.benefitSmartBody': 'AI merangkum catatan panjang jadi kartu fokus.',
  'hero.benefitYours': 'Milik Anda',
  'hero.benefitYoursBody': 'Data tersimpan aman, akses kapan saja, dari perangkat apa pun.',
  'hero.benefitTitle': 'Kenapa FlashMind?',
  'hero.socialProof': 'Dipercaya pelajar di seluruh Indonesia',
  'hero.finalTitle': 'Mulai gratis. Tanpa kartu kredit.',
  'hero.finalBody': 'Uji coba tanpa akun, atau daftar gratis dan simpan kartu selamanya.',
  'auth.toggleLogin': 'Masuk',
  'auth.toggleRegister': 'Daftar',
  'auth.email': 'Surel',
  'auth.password': 'Kata sandi',
  'auth.passwordConfirm': 'Konfirmasi kata sandi',
  'auth.firstName': 'Nama Depan',
  'auth.lastName': 'Nama Belakang',
  'auth.gender': 'Jenis Kelamin',
  'auth.genderMale': 'Laki-laki',
  'auth.genderFemale': 'Perempuan',
  'auth.genderOther': 'Lainnya',
  'auth.submitLogin': 'Masuk',
  'auth.submitRegister': 'Daftar',
  'auth.google': 'Masuk dengan Google',
  'auth.googleUnavailable': 'Masuk dengan Google (tidak tersedia)',
  'dashboard.title': 'Kartu Belajar Saya',
  'dashboard.empty': 'Belum ada kartu belajar',
  'dashboard.guestEmpty': 'Mode uji coba. Daftar untuk mulai menyimpan kartu belajar Anda.',
  'dashboard.guestBadge': 'Mode uji coba',
  'dashboard.guestBanner': 'Anda masuk sebagai tamu. Buat akun gratis untuk menyimpan kartu belajar Anda.',
  'dashboard.guestCta': 'Daftar gratis',
  'dashboard.newManual': '+ Kartu Baru',
  'dashboard.aiGen': '✨ Buat dengan AI',
  'flashcard.front': 'Judul',
  'flashcard.back': 'Catatan',
  'flashcard.delete': 'Hapus',
  'flashcard.save': 'Simpan',
  'flashcard.close': 'Tutup',
  'ai.promptLabel': 'Catatan Anda',
  'ai.generate': 'Hasilkan',
  'ai.loading': 'Memuat…',
  'ai.noKey': 'Fitur AI belum dikonfigurasi',
  'ai.failed': 'AI gagal membuat kartu',
  'admin.title': 'Admin',
  'admin.keyPlaceholder': 'Kunci API admin',
  'admin.saveKey': 'Simpan kunci',
  'admin.clearKey': 'Hapus kunci',
  'admin.stats': 'Statistik',
  'admin.totalUsers': 'Total pengguna',
  'admin.totalGuests': 'Total tamu',
  'admin.totalCards': 'Total kartu',
  'admin.latestTraces': 'Jejak terbaru',
  'error.required': 'Wajib diisi',
  'error.emailInvalid': 'Format surel tidak valid',
  'error.passwordShort': 'Kata sandi minimal 8 karakter',
  'error.passwordMismatch': 'Kata sandi tidak cocok',
  'error.unauthorized': 'Tidak diizinkan',
  'error.network': 'Koneksi bermasalah',
  'error.serverError': 'Terjadi kesalahan server',
  'error.tooManyRequests': 'Terlalu banyak permintaan',
  'footer.credit': '© FlashMind',
} as const;

export default id;

export function t(key: keyof typeof id): string {
  return id[key];
}